# Generated by Django 5.1.6 on 2025-04-11 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('asset_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('asset_name', models.CharField(max_length=255)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=65535)),
                ('serial_no', models.CharField(blank=True, max_length=225, null=True)),
                ('content_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'db_table': 'assets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemMasterData',
            fields=[
                ('item_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('item_type', models.CharField(choices=[('Product', 'Product'), ('Raw Material', 'Raw Material'), ('Asset', 'Asset')], default='Product', max_length=20)),
                ('unit_of_measure', models.CharField(choices=[('kg', 'kg'), ('sh', 'sh'), ('bx', 'bx'), ('l', 'l'), ('m', 'm'), ('gal', 'gal'), ('pcs', 'pcs'), ('set', 'set'), ('mm', 'mm'), ('unit', 'unit')], max_length=5)),
                ('item_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Blocked', 'Blocked')], default='Active', max_length=20)),
                ('manage_item_by', models.CharField(choices=[('Serial', 'Serial Number'), ('Batches', 'Batches'), ('None', 'None')], default='Batches', max_length=20)),
                ('preferred_vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('purchasing_uom', models.CharField(choices=[('kg', 'kg'), ('sh', 'sh'), ('bx', 'bx'), ('l', 'l'), ('m', 'm'), ('gal', 'gal'), ('pcs', 'pcs'), ('set', 'set'), ('mm', 'mm'), ('unit', 'unit')], max_length=5)),
                ('items_per_purchase_unit', models.IntegerField(blank=True, null=True)),
                ('purchase_quantity_per_package', models.IntegerField(blank=True, null=True)),
                ('sales_uom', models.CharField(choices=[('kg', 'kg'), ('sh', 'sh'), ('bx', 'bx'), ('l', 'l'), ('m', 'm'), ('gal', 'gal'), ('pcs', 'pcs'), ('set', 'set'), ('mm', 'mm'), ('unit', 'unit')], max_length=5)),
                ('items_per_sale_unit', models.IntegerField(blank=True, null=True)),
                ('sales_quantity_per_package', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Item Master Data',
                'verbose_name_plural': 'Item Master Data',
                'db_table': 'item_master_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Policies',
            fields=[
                ('policy_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('policy_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Blocked', 'Blocked')], default='Active', max_length=20)),
            ],
            options={
                'db_table': 'policies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=65535)),
                ('stock_level', models.IntegerField(blank=True, null=True)),
                ('unit_of_measure', models.CharField(choices=[('kg', 'kg'), ('sh', 'sh'), ('bx', 'bx'), ('l', 'l'), ('m', 'm'), ('gal', 'gal'), ('pcs', 'pcs'), ('set', 'set'), ('mm', 'mm'), ('unit', 'unit')], default='set', max_length=5)),
                ('batch_no', models.CharField(blank=True, max_length=255, null=True)),
                ('item_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Blocked', 'Blocked')], default='Active', max_length=20)),
                ('warranty_period', models.IntegerField(blank=True, null=True)),
                ('content_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawMaterials',
            fields=[
                ('material_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('material_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit_of_measure', models.CharField(choices=[('kg', 'kg'), ('sh', 'sh'), ('bx', 'bx'), ('l', 'l'), ('m', 'm'), ('gal', 'gal'), ('pcs', 'pcs'), ('set', 'set'), ('mm', 'mm'), ('unit', 'unit')], default='kg', max_length=5)),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=65535, null=True)),
            ],
            options={
                'verbose_name': 'Raw Material',
                'verbose_name_plural': 'Raw Materials',
                'db_table': 'raw_materials',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('application_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vendor',
                'managed': False,
            },
        ),
    ]
