# Generated by Django 5.1.6 on 2025-04-14 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_master_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policies',
            options={'managed': False, 'verbose_name': 'Policy', 'verbose_name_plural': 'Policies'},
        ),
    ]
