# Generated by Django 5.1.6 on 2025-05-04 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_master_list', '0002_alter_policies_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assets',
        ),
        migrations.DeleteModel(
            name='Policies',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='RawMaterials',
        ),
        migrations.AlterModelTable(
            name='itemmasterdata',
            table='"admin"."item_master_data"',
        ),
        migrations.AlterModelTable(
            name='vendor',
            table='"purchasing"."vendors"',
        ),
    ]
