# Generated by Django 5.1.6 on 2025-04-11 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('warehouse_location', models.CharField(max_length=255)),
                ('stored_materials', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
                'db_table': 'warehouse',
                'managed': False,
            },
        ),
    ]
