# Generated by Django 5.1.6 on 2025-05-04 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='warehouse',
            table='"admin"."warehouse"',
        ),
    ]
