# Generated by Django 5.1.6 on 2025-04-11 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPartnerMaster',
            fields=[
                ('partner_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('customer_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('partner_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Employee', 'Employee'), ('Vendor', 'Vendor')], max_length=20)),
                ('contact_info', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Business Partner',
                'verbose_name_plural': 'Business Partners',
                'db_table': 'business_partner_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('application_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Blocked', 'Blocked')], default='Active', max_length=20)),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'db_table': 'vendor',
                'managed': False,
            },
        ),
    ]
