# Generated by Django 5.1.6 on 2025-05-04 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_partner_master_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='businesspartnermaster',
            table='"admin"."business_partner_master"',
        ),
        migrations.AlterModelTable(
            name='vendor',
            table='"purchasing"."vendors"',
        ),
    ]
