# Generated by Django 5.1.6 on 2025-04-21 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policies',
            fields=[
                ('policy_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('policy_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
            ],
            options={
                'verbose_name': 'Policy',
                'verbose_name_plural': 'Policies',
                'db_table': '"admin"."policies"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PolicyDocument',
            fields=[
                ('policy_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('document', models.URLField(max_length=1000)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'policies_policydocument',
                'managed': False,
            },
        ),
    ]
