# Generated by Django 5.1.6 on 2025-05-03 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PolicyDocument',
        ),
    ]
