# Generated by Django 5.1.6 on 2025-04-14 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='policies',
            table='"admin"."policies"',
        ),
        migrations.CreateModel(
            name='PolicyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='policy_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy_document', to='policies.policies')),
            ],
        ),
    ]
