# Generated by Django 5.1.6 on 2025-04-14 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_alter_policies_table_policydocument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policies',
            options={'managed': True, 'verbose_name': 'Policy', 'verbose_name_plural': 'Policies'},
        ),
        migrations.RemoveField(
            model_name='policydocument',
            name='id',
        ),
        migrations.AlterField(
            model_name='policydocument',
            name='policy',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='document_file', serialize=False, to='policies.policies'),
        ),
    ]
